name: Despliegue Automatizado a Vercel
on:
  push:
    branches: [ main ] # Cambia a 'master' si es el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-level: 18

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Desplegar a Producción
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}